<template><h1 id="如何封装一个javascript的类型判断函数" tabindex="-1"><a class="header-anchor" href="#如何封装一个javascript的类型判断函数" aria-hidden="true">#</a> 如何封装一个javascript的类型判断函数</h1>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">isType</span><span class="token punctuation">(</span><span class="token parameter">source</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> target <span class="token operator">=</span> <span class="token class-name">Object</span><span class="token punctuation">.</span>prototype<span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">.</span><span class="token function">call</span><span class="token punctuation">(</span>source<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">switch</span><span class="token punctuation">(</span>target<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">case</span> <span class="token string">"[object Null]"</span><span class="token operator">:</span>
            <span class="token keyword">return</span> <span class="token string">'null'</span><span class="token punctuation">;</span>
        <span class="token keyword">case</span> <span class="token string">"[object Undefined]"</span><span class="token operator">:</span>
            <span class="token keyword">return</span> <span class="token string">'undefined'</span><span class="token punctuation">;</span>
        <span class="token keyword">case</span> <span class="token string">"[object String]"</span><span class="token operator">:</span>
            <span class="token keyword">return</span> <span class="token string">'string'</span><span class="token punctuation">;</span>
        <span class="token keyword">case</span> <span class="token string">"[object Number]"</span><span class="token operator">:</span>
            <span class="token keyword">return</span> <span class="token string">'number'</span><span class="token punctuation">;</span>
        <span class="token keyword">case</span> <span class="token string">"[object Boolean]"</span><span class="token operator">:</span>
            <span class="token keyword">return</span> <span class="token string">'boolean'</span><span class="token punctuation">;</span>
        <span class="token keyword">case</span> <span class="token string">"[object Object]"</span><span class="token operator">:</span>
            <span class="token keyword">return</span> <span class="token string">'object'</span><span class="token punctuation">;</span>
        <span class="token keyword">case</span> <span class="token string">"[object Array]"</span><span class="token operator">:</span>
            <span class="token keyword">return</span> <span class="token string">'array'</span><span class="token punctuation">;</span>
        <span class="token keyword">case</span> <span class="token string">"[object Function]"</span><span class="token operator">:</span>
            <span class="token keyword">return</span> <span class="token string">'function'</span><span class="token punctuation">;</span>
        <span class="token keyword">case</span> <span class="token string">"[object Date]"</span><span class="token operator">:</span>
            <span class="token keyword">return</span> <span class="token string">'date'</span><span class="token punctuation">;</span>
        <span class="token keyword">case</span> <span class="token string">"[object RegExp]"</span><span class="token operator">:</span>
            <span class="token keyword">return</span> <span class="token string">'regexp'</span><span class="token punctuation">;</span>
        <span class="token keyword">case</span> <span class="token string">"[object Error]"</span><span class="token operator">:</span>
            <span class="token keyword">return</span> <span class="token string">'error'</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token keyword">function</span> <span class="token function">getType</span><span class="token punctuation">(</span><span class="token parameter">target</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token class-name">Object</span><span class="token punctuation">.</span>prototype<span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">.</span><span class="token function">call</span><span class="token punctuation">(</span>target<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br></div></div><div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">typeOf</span><span class="token punctuation">(</span><span class="token parameter">obj</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">let</span> res <span class="token operator">=</span> <span class="token class-name">Object</span><span class="token punctuation">.</span>prototype<span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">.</span><span class="token function">call</span><span class="token punctuation">(</span>obj<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">split</span><span class="token punctuation">(</span><span class="token string">" "</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span>
    res <span class="token operator">=</span> res<span class="token punctuation">.</span><span class="token function">substring</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> res<span class="token punctuation">.</span>length <span class="token operator">-</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toLowerCase</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token keyword">return</span> res
<span class="token punctuation">}</span>
<span class="token function">typeOf</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token comment">// array</span>
<span class="token function">typeOf</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token comment">// object</span>
<span class="token function">typeOf</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">// date</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div></template>
